# Generated by Django 5.0.4 on 2024-04-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('station_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=30)),
                ('to_location', models.CharField(max_length=30)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.station')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
    ]
