# Generated by Django 5.0.3 on 2024-04-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='train.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='train.place'),
        ),
    ]
