# Generated by Django 4.2.5 on 2024-04-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_employee'),
        ('train', '0002_place_alter_route_from_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('class_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_start_range', models.IntegerField()),
                ('seat_end_range', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.classtype')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.trainclass')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_journey', models.DateField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.route')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.seat')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail')),
            ],
        ),
    ]
