# Generated by Django 4.2.5 on 2024-04-04 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_classtype_trainclass_seat_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
