# Generated by Django 4.2.5 on 2024-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_route_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainclass',
            name='price',
            field=models.IntegerField(default=250),
        ),
    ]
