# Generated by Django 4.2.5 on 2024-04-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_trainclass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='train.trainclass'),
            preserve_default=False,
        ),
    ]
