# Generated by Django 4.2.5 on 2024-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_booking_class_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainclass',
            name='no_of_seat_filled',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
