# Generated by Django 4.2.5 on 2024-04-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_trainclass_no_of_seat_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainclass',
            name='no_of_seat_filled',
        ),
    ]
