# Generated by Django 4.2.5 on 2024-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_remove_trainclass_no_of_seat_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(),
        ),
    ]
