# Generated by Django 4.2.5 on 2024-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_alter_booking_seat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainclass',
            name='id',
        ),
        migrations.AddField(
            model_name='trainclass',
            name='class_pk',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
