# Generated by Django 4.2.5 on 2024-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_remove_trainclass_id_trainclass_class_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainclass',
            name='class_pk',
        ),
        migrations.AddField(
            model_name='trainclass',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
